export class Constant {
  /**
   * The router Page url.
   */
  static readonly ROUTER_PAGE_URL: string = '@bundle:com.advanced.temp/TaroWebContainer/ets/webrouterservice/pagemanager/PageTemplate';
  /**
   * The URL of first page
   */
  static readonly URL_FIRST_PAGE: string = 'resource://rawfile/index.html';
  static readonly URL_FIRST_PAGE1: string = '';
  /**
   * ?from = native
   */
  static readonly FROM_NATIVE: string = '?from=native';
  /**
   * The end of first webPage's URL
   */
  static readonly END_FIRST_URL: string = '/index/index';
}