export class ImageViewerConstants {
  // 缩放动画的持续时间
  static readonly ANIMATE_DURATION: number = 200;
  // swiper中缓存图片的数量
  static readonly SWIPER_CACHE_COUNT: number = 5;
  // swiper中ImageItem的宽度
  static readonly IMAGE_ITEM_WIDTH: string = '100%';
  // swiper中ImageItem的高度
  static readonly IMAGE_ITEM_HEIGHT: string = '100%';
  // swiper的宽度
  static readonly SWIPER_WIDTH: string = '100%';
  // swiper的高度
  static readonly SWIPER_HEIGHT: string = '100%';
  // 图片默认最大缩放值
  static readonly MAX_SCALE_VALUE: number = 3;
  // 图片默认额外缩放值
  static readonly EXTRA_SCALE_VALUE: number = 0.5;
  // 图片预览模态窗背景色
  static readonly IMAGE_VIEWER_BACKGROUND_COLOR: string = '#ff000000';
  // 图片加载中Loading图标高度
  static readonly LOADING_IMAGE_HEIGHT: number = 200;
}